// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: navigation_service.proto

#include "navigation_service.pb.h"
#include "navigation_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* NavigationService_method_names[] = {
  "/NavigationService/StreamNavigationData",
};

std::unique_ptr< NavigationService::Stub> NavigationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NavigationService::Stub> stub(new NavigationService::Stub(channel, options));
  return stub;
}

NavigationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamNavigationData_(NavigationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::NavigationData>* NavigationService::Stub::StreamNavigationDataRaw(::grpc::ClientContext* context, const ::StreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::NavigationData>::Create(channel_.get(), rpcmethod_StreamNavigationData_, context, request);
}

void NavigationService::Stub::async::StreamNavigationData(::grpc::ClientContext* context, const ::StreamRequest* request, ::grpc::ClientReadReactor< ::NavigationData>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::NavigationData>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamNavigationData_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::NavigationData>* NavigationService::Stub::AsyncStreamNavigationDataRaw(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::NavigationData>::Create(channel_.get(), cq, rpcmethod_StreamNavigationData_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::NavigationData>* NavigationService::Stub::PrepareAsyncStreamNavigationDataRaw(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::NavigationData>::Create(channel_.get(), cq, rpcmethod_StreamNavigationData_, context, request, false, nullptr);
}

NavigationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NavigationService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< NavigationService::Service, ::StreamRequest, ::NavigationData>(
          [](NavigationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::StreamRequest* req,
             ::grpc::ServerWriter<::NavigationData>* writer) {
               return service->StreamNavigationData(ctx, req, writer);
             }, this)));
}

NavigationService::Service::~Service() {
}

::grpc::Status NavigationService::Service::StreamNavigationData(::grpc::ServerContext* context, const ::StreamRequest* request, ::grpc::ServerWriter< ::NavigationData>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


