// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: navigation_service.proto

#include "navigation_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR StreamRequest::StreamRequest(
    ::_pbi::ConstantInitialized) {}
struct StreamRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamRequestDefaultTypeInternal() {}
  union {
    StreamRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamRequestDefaultTypeInternal _StreamRequest_default_instance_;
PROTOBUF_CONSTEXPR DoubleField::DoubleField(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.value_)*/0
  , /*decltype(_impl_.is_valid_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DoubleFieldDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DoubleFieldDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DoubleFieldDefaultTypeInternal() {}
  union {
    DoubleField _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DoubleFieldDefaultTypeInternal _DoubleField_default_instance_;
PROTOBUF_CONSTEXPR NavigationData::NavigationData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.latitude_dd_)*/nullptr
  , /*decltype(_impl_.longitude_dd_)*/nullptr
  , /*decltype(_impl_.heading_rad_)*/nullptr
  , /*decltype(_impl_.relative_speed_knots_)*/nullptr
  , /*decltype(_impl_.roll_rad_)*/nullptr
  , /*decltype(_impl_.pitch_rad_)*/nullptr
  , /*decltype(_impl_.drift_speed_mps_)*/nullptr
  , /*decltype(_impl_.drift_course_mps_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct NavigationDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NavigationDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NavigationDataDefaultTypeInternal() {}
  union {
    NavigationData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NavigationDataDefaultTypeInternal _NavigationData_default_instance_;
static ::_pb::Metadata file_level_metadata_navigation_5fservice_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_navigation_5fservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_navigation_5fservice_2eproto = nullptr;

const uint32_t TableStruct_navigation_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::StreamRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DoubleField, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DoubleField, _impl_.value_),
  PROTOBUF_FIELD_OFFSET(::DoubleField, _impl_.is_valid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NavigationData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::NavigationData, _impl_.latitude_dd_),
  PROTOBUF_FIELD_OFFSET(::NavigationData, _impl_.longitude_dd_),
  PROTOBUF_FIELD_OFFSET(::NavigationData, _impl_.heading_rad_),
  PROTOBUF_FIELD_OFFSET(::NavigationData, _impl_.relative_speed_knots_),
  PROTOBUF_FIELD_OFFSET(::NavigationData, _impl_.roll_rad_),
  PROTOBUF_FIELD_OFFSET(::NavigationData, _impl_.pitch_rad_),
  PROTOBUF_FIELD_OFFSET(::NavigationData, _impl_.drift_speed_mps_),
  PROTOBUF_FIELD_OFFSET(::NavigationData, _impl_.drift_course_mps_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::StreamRequest)},
  { 6, -1, -1, sizeof(::DoubleField)},
  { 14, -1, -1, sizeof(::NavigationData)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_StreamRequest_default_instance_._instance,
  &::_DoubleField_default_instance_._instance,
  &::_NavigationData_default_instance_._instance,
};

const char descriptor_table_protodef_navigation_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030navigation_service.proto\"\017\n\rStreamRequ"
  "est\".\n\013DoubleField\022\r\n\005value\030\001 \001(\001\022\020\n\010is_"
  "valid\030\002 \001(\010\"\266\002\n\016NavigationData\022!\n\013latitu"
  "de_dd\030\001 \001(\0132\014.DoubleField\022\"\n\014longitude_d"
  "d\030\002 \001(\0132\014.DoubleField\022!\n\013heading_rad\030\003 \001"
  "(\0132\014.DoubleField\022*\n\024relative_speed_knots"
  "\030\004 \001(\0132\014.DoubleField\022\036\n\010roll_rad\030\005 \001(\0132\014"
  ".DoubleField\022\037\n\tpitch_rad\030\006 \001(\0132\014.Double"
  "Field\022%\n\017drift_speed_mps\030\007 \001(\0132\014.DoubleF"
  "ield\022&\n\020drift_course_mps\030\010 \001(\0132\014.DoubleF"
  "ield2P\n\021NavigationService\022;\n\024StreamNavig"
  "ationData\022\016.StreamRequest\032\017.NavigationDa"
  "ta\"\0000\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_navigation_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_navigation_5fservice_2eproto = {
    false, false, 494, descriptor_table_protodef_navigation_5fservice_2eproto,
    "navigation_service.proto",
    &descriptor_table_navigation_5fservice_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_navigation_5fservice_2eproto::offsets,
    file_level_metadata_navigation_5fservice_2eproto, file_level_enum_descriptors_navigation_5fservice_2eproto,
    file_level_service_descriptors_navigation_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_navigation_5fservice_2eproto_getter() {
  return &descriptor_table_navigation_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_navigation_5fservice_2eproto(&descriptor_table_navigation_5fservice_2eproto);

// ===================================================================

class StreamRequest::_Internal {
 public:
};

StreamRequest::StreamRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:StreamRequest)
}
StreamRequest::StreamRequest(const StreamRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  StreamRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:StreamRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StreamRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StreamRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata StreamRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_navigation_5fservice_2eproto_getter, &descriptor_table_navigation_5fservice_2eproto_once,
      file_level_metadata_navigation_5fservice_2eproto[0]);
}

// ===================================================================

class DoubleField::_Internal {
 public:
};

DoubleField::DoubleField(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DoubleField)
}
DoubleField::DoubleField(const DoubleField& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DoubleField* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){}
    , decltype(_impl_.is_valid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.value_, &from._impl_.value_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_valid_) -
    reinterpret_cast<char*>(&_impl_.value_)) + sizeof(_impl_.is_valid_));
  // @@protoc_insertion_point(copy_constructor:DoubleField)
}

inline void DoubleField::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){0}
    , decltype(_impl_.is_valid_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DoubleField::~DoubleField() {
  // @@protoc_insertion_point(destructor:DoubleField)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DoubleField::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DoubleField::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DoubleField::Clear() {
// @@protoc_insertion_point(message_clear_start:DoubleField)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.value_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_valid_) -
      reinterpret_cast<char*>(&_impl_.value_)) + sizeof(_impl_.is_valid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DoubleField::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // bool is_valid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.is_valid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DoubleField::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DoubleField)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double value = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_value = this->_internal_value();
  uint64_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_value(), target);
  }

  // bool is_valid = 2;
  if (this->_internal_is_valid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_is_valid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DoubleField)
  return target;
}

size_t DoubleField::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DoubleField)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double value = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_value = this->_internal_value();
  uint64_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    total_size += 1 + 8;
  }

  // bool is_valid = 2;
  if (this->_internal_is_valid() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DoubleField::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DoubleField::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DoubleField::GetClassData() const { return &_class_data_; }


void DoubleField::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DoubleField*>(&to_msg);
  auto& from = static_cast<const DoubleField&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DoubleField)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_value = from._internal_value();
  uint64_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_is_valid() != 0) {
    _this->_internal_set_is_valid(from._internal_is_valid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DoubleField::CopyFrom(const DoubleField& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DoubleField)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DoubleField::IsInitialized() const {
  return true;
}

void DoubleField::InternalSwap(DoubleField* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DoubleField, _impl_.is_valid_)
      + sizeof(DoubleField::_impl_.is_valid_)
      - PROTOBUF_FIELD_OFFSET(DoubleField, _impl_.value_)>(
          reinterpret_cast<char*>(&_impl_.value_),
          reinterpret_cast<char*>(&other->_impl_.value_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DoubleField::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_navigation_5fservice_2eproto_getter, &descriptor_table_navigation_5fservice_2eproto_once,
      file_level_metadata_navigation_5fservice_2eproto[1]);
}

// ===================================================================

class NavigationData::_Internal {
 public:
  static const ::DoubleField& latitude_dd(const NavigationData* msg);
  static const ::DoubleField& longitude_dd(const NavigationData* msg);
  static const ::DoubleField& heading_rad(const NavigationData* msg);
  static const ::DoubleField& relative_speed_knots(const NavigationData* msg);
  static const ::DoubleField& roll_rad(const NavigationData* msg);
  static const ::DoubleField& pitch_rad(const NavigationData* msg);
  static const ::DoubleField& drift_speed_mps(const NavigationData* msg);
  static const ::DoubleField& drift_course_mps(const NavigationData* msg);
};

const ::DoubleField&
NavigationData::_Internal::latitude_dd(const NavigationData* msg) {
  return *msg->_impl_.latitude_dd_;
}
const ::DoubleField&
NavigationData::_Internal::longitude_dd(const NavigationData* msg) {
  return *msg->_impl_.longitude_dd_;
}
const ::DoubleField&
NavigationData::_Internal::heading_rad(const NavigationData* msg) {
  return *msg->_impl_.heading_rad_;
}
const ::DoubleField&
NavigationData::_Internal::relative_speed_knots(const NavigationData* msg) {
  return *msg->_impl_.relative_speed_knots_;
}
const ::DoubleField&
NavigationData::_Internal::roll_rad(const NavigationData* msg) {
  return *msg->_impl_.roll_rad_;
}
const ::DoubleField&
NavigationData::_Internal::pitch_rad(const NavigationData* msg) {
  return *msg->_impl_.pitch_rad_;
}
const ::DoubleField&
NavigationData::_Internal::drift_speed_mps(const NavigationData* msg) {
  return *msg->_impl_.drift_speed_mps_;
}
const ::DoubleField&
NavigationData::_Internal::drift_course_mps(const NavigationData* msg) {
  return *msg->_impl_.drift_course_mps_;
}
NavigationData::NavigationData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:NavigationData)
}
NavigationData::NavigationData(const NavigationData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  NavigationData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.latitude_dd_){nullptr}
    , decltype(_impl_.longitude_dd_){nullptr}
    , decltype(_impl_.heading_rad_){nullptr}
    , decltype(_impl_.relative_speed_knots_){nullptr}
    , decltype(_impl_.roll_rad_){nullptr}
    , decltype(_impl_.pitch_rad_){nullptr}
    , decltype(_impl_.drift_speed_mps_){nullptr}
    , decltype(_impl_.drift_course_mps_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_latitude_dd()) {
    _this->_impl_.latitude_dd_ = new ::DoubleField(*from._impl_.latitude_dd_);
  }
  if (from._internal_has_longitude_dd()) {
    _this->_impl_.longitude_dd_ = new ::DoubleField(*from._impl_.longitude_dd_);
  }
  if (from._internal_has_heading_rad()) {
    _this->_impl_.heading_rad_ = new ::DoubleField(*from._impl_.heading_rad_);
  }
  if (from._internal_has_relative_speed_knots()) {
    _this->_impl_.relative_speed_knots_ = new ::DoubleField(*from._impl_.relative_speed_knots_);
  }
  if (from._internal_has_roll_rad()) {
    _this->_impl_.roll_rad_ = new ::DoubleField(*from._impl_.roll_rad_);
  }
  if (from._internal_has_pitch_rad()) {
    _this->_impl_.pitch_rad_ = new ::DoubleField(*from._impl_.pitch_rad_);
  }
  if (from._internal_has_drift_speed_mps()) {
    _this->_impl_.drift_speed_mps_ = new ::DoubleField(*from._impl_.drift_speed_mps_);
  }
  if (from._internal_has_drift_course_mps()) {
    _this->_impl_.drift_course_mps_ = new ::DoubleField(*from._impl_.drift_course_mps_);
  }
  // @@protoc_insertion_point(copy_constructor:NavigationData)
}

inline void NavigationData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.latitude_dd_){nullptr}
    , decltype(_impl_.longitude_dd_){nullptr}
    , decltype(_impl_.heading_rad_){nullptr}
    , decltype(_impl_.relative_speed_knots_){nullptr}
    , decltype(_impl_.roll_rad_){nullptr}
    , decltype(_impl_.pitch_rad_){nullptr}
    , decltype(_impl_.drift_speed_mps_){nullptr}
    , decltype(_impl_.drift_course_mps_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

NavigationData::~NavigationData() {
  // @@protoc_insertion_point(destructor:NavigationData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void NavigationData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.latitude_dd_;
  if (this != internal_default_instance()) delete _impl_.longitude_dd_;
  if (this != internal_default_instance()) delete _impl_.heading_rad_;
  if (this != internal_default_instance()) delete _impl_.relative_speed_knots_;
  if (this != internal_default_instance()) delete _impl_.roll_rad_;
  if (this != internal_default_instance()) delete _impl_.pitch_rad_;
  if (this != internal_default_instance()) delete _impl_.drift_speed_mps_;
  if (this != internal_default_instance()) delete _impl_.drift_course_mps_;
}

void NavigationData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void NavigationData::Clear() {
// @@protoc_insertion_point(message_clear_start:NavigationData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.latitude_dd_ != nullptr) {
    delete _impl_.latitude_dd_;
  }
  _impl_.latitude_dd_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.longitude_dd_ != nullptr) {
    delete _impl_.longitude_dd_;
  }
  _impl_.longitude_dd_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.heading_rad_ != nullptr) {
    delete _impl_.heading_rad_;
  }
  _impl_.heading_rad_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.relative_speed_knots_ != nullptr) {
    delete _impl_.relative_speed_knots_;
  }
  _impl_.relative_speed_knots_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.roll_rad_ != nullptr) {
    delete _impl_.roll_rad_;
  }
  _impl_.roll_rad_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.pitch_rad_ != nullptr) {
    delete _impl_.pitch_rad_;
  }
  _impl_.pitch_rad_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.drift_speed_mps_ != nullptr) {
    delete _impl_.drift_speed_mps_;
  }
  _impl_.drift_speed_mps_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.drift_course_mps_ != nullptr) {
    delete _impl_.drift_course_mps_;
  }
  _impl_.drift_course_mps_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NavigationData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .DoubleField latitude_dd = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_latitude_dd(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .DoubleField longitude_dd = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_longitude_dd(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .DoubleField heading_rad = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_heading_rad(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .DoubleField relative_speed_knots = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_relative_speed_knots(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .DoubleField roll_rad = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_roll_rad(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .DoubleField pitch_rad = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_pitch_rad(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .DoubleField drift_speed_mps = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_drift_speed_mps(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .DoubleField drift_course_mps = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_drift_course_mps(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* NavigationData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NavigationData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .DoubleField latitude_dd = 1;
  if (this->_internal_has_latitude_dd()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::latitude_dd(this),
        _Internal::latitude_dd(this).GetCachedSize(), target, stream);
  }

  // .DoubleField longitude_dd = 2;
  if (this->_internal_has_longitude_dd()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::longitude_dd(this),
        _Internal::longitude_dd(this).GetCachedSize(), target, stream);
  }

  // .DoubleField heading_rad = 3;
  if (this->_internal_has_heading_rad()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::heading_rad(this),
        _Internal::heading_rad(this).GetCachedSize(), target, stream);
  }

  // .DoubleField relative_speed_knots = 4;
  if (this->_internal_has_relative_speed_knots()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::relative_speed_knots(this),
        _Internal::relative_speed_knots(this).GetCachedSize(), target, stream);
  }

  // .DoubleField roll_rad = 5;
  if (this->_internal_has_roll_rad()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::roll_rad(this),
        _Internal::roll_rad(this).GetCachedSize(), target, stream);
  }

  // .DoubleField pitch_rad = 6;
  if (this->_internal_has_pitch_rad()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::pitch_rad(this),
        _Internal::pitch_rad(this).GetCachedSize(), target, stream);
  }

  // .DoubleField drift_speed_mps = 7;
  if (this->_internal_has_drift_speed_mps()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::drift_speed_mps(this),
        _Internal::drift_speed_mps(this).GetCachedSize(), target, stream);
  }

  // .DoubleField drift_course_mps = 8;
  if (this->_internal_has_drift_course_mps()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::drift_course_mps(this),
        _Internal::drift_course_mps(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NavigationData)
  return target;
}

size_t NavigationData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NavigationData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .DoubleField latitude_dd = 1;
  if (this->_internal_has_latitude_dd()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.latitude_dd_);
  }

  // .DoubleField longitude_dd = 2;
  if (this->_internal_has_longitude_dd()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.longitude_dd_);
  }

  // .DoubleField heading_rad = 3;
  if (this->_internal_has_heading_rad()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.heading_rad_);
  }

  // .DoubleField relative_speed_knots = 4;
  if (this->_internal_has_relative_speed_knots()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.relative_speed_knots_);
  }

  // .DoubleField roll_rad = 5;
  if (this->_internal_has_roll_rad()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.roll_rad_);
  }

  // .DoubleField pitch_rad = 6;
  if (this->_internal_has_pitch_rad()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.pitch_rad_);
  }

  // .DoubleField drift_speed_mps = 7;
  if (this->_internal_has_drift_speed_mps()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.drift_speed_mps_);
  }

  // .DoubleField drift_course_mps = 8;
  if (this->_internal_has_drift_course_mps()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.drift_course_mps_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NavigationData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    NavigationData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NavigationData::GetClassData() const { return &_class_data_; }


void NavigationData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<NavigationData*>(&to_msg);
  auto& from = static_cast<const NavigationData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NavigationData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_latitude_dd()) {
    _this->_internal_mutable_latitude_dd()->::DoubleField::MergeFrom(
        from._internal_latitude_dd());
  }
  if (from._internal_has_longitude_dd()) {
    _this->_internal_mutable_longitude_dd()->::DoubleField::MergeFrom(
        from._internal_longitude_dd());
  }
  if (from._internal_has_heading_rad()) {
    _this->_internal_mutable_heading_rad()->::DoubleField::MergeFrom(
        from._internal_heading_rad());
  }
  if (from._internal_has_relative_speed_knots()) {
    _this->_internal_mutable_relative_speed_knots()->::DoubleField::MergeFrom(
        from._internal_relative_speed_knots());
  }
  if (from._internal_has_roll_rad()) {
    _this->_internal_mutable_roll_rad()->::DoubleField::MergeFrom(
        from._internal_roll_rad());
  }
  if (from._internal_has_pitch_rad()) {
    _this->_internal_mutable_pitch_rad()->::DoubleField::MergeFrom(
        from._internal_pitch_rad());
  }
  if (from._internal_has_drift_speed_mps()) {
    _this->_internal_mutable_drift_speed_mps()->::DoubleField::MergeFrom(
        from._internal_drift_speed_mps());
  }
  if (from._internal_has_drift_course_mps()) {
    _this->_internal_mutable_drift_course_mps()->::DoubleField::MergeFrom(
        from._internal_drift_course_mps());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void NavigationData::CopyFrom(const NavigationData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NavigationData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NavigationData::IsInitialized() const {
  return true;
}

void NavigationData::InternalSwap(NavigationData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NavigationData, _impl_.drift_course_mps_)
      + sizeof(NavigationData::_impl_.drift_course_mps_)
      - PROTOBUF_FIELD_OFFSET(NavigationData, _impl_.latitude_dd_)>(
          reinterpret_cast<char*>(&_impl_.latitude_dd_),
          reinterpret_cast<char*>(&other->_impl_.latitude_dd_));
}

::PROTOBUF_NAMESPACE_ID::Metadata NavigationData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_navigation_5fservice_2eproto_getter, &descriptor_table_navigation_5fservice_2eproto_once,
      file_level_metadata_navigation_5fservice_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::StreamRequest*
Arena::CreateMaybeMessage< ::StreamRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::StreamRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::DoubleField*
Arena::CreateMaybeMessage< ::DoubleField >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DoubleField >(arena);
}
template<> PROTOBUF_NOINLINE ::NavigationData*
Arena::CreateMaybeMessage< ::NavigationData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NavigationData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
