// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: navigation_service.proto
#ifndef GRPC_navigation_5fservice_2eproto__INCLUDED
#define GRPC_navigation_5fservice_2eproto__INCLUDED

#include "navigation_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class NavigationService final {
 public:
  static constexpr char const* service_full_name() {
    return "NavigationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::NavigationData>> StreamNavigationData(::grpc::ClientContext* context, const ::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::NavigationData>>(StreamNavigationDataRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::NavigationData>> AsyncStreamNavigationData(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::NavigationData>>(AsyncStreamNavigationDataRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::NavigationData>> PrepareAsyncStreamNavigationData(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::NavigationData>>(PrepareAsyncStreamNavigationDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamNavigationData(::grpc::ClientContext* context, const ::StreamRequest* request, ::grpc::ClientReadReactor< ::NavigationData>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::NavigationData>* StreamNavigationDataRaw(::grpc::ClientContext* context, const ::StreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::NavigationData>* AsyncStreamNavigationDataRaw(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::NavigationData>* PrepareAsyncStreamNavigationDataRaw(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::NavigationData>> StreamNavigationData(::grpc::ClientContext* context, const ::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::NavigationData>>(StreamNavigationDataRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::NavigationData>> AsyncStreamNavigationData(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::NavigationData>>(AsyncStreamNavigationDataRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::NavigationData>> PrepareAsyncStreamNavigationData(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::NavigationData>>(PrepareAsyncStreamNavigationDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamNavigationData(::grpc::ClientContext* context, const ::StreamRequest* request, ::grpc::ClientReadReactor< ::NavigationData>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::NavigationData>* StreamNavigationDataRaw(::grpc::ClientContext* context, const ::StreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::NavigationData>* AsyncStreamNavigationDataRaw(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::NavigationData>* PrepareAsyncStreamNavigationDataRaw(::grpc::ClientContext* context, const ::StreamRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamNavigationData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamNavigationData(::grpc::ServerContext* context, const ::StreamRequest* request, ::grpc::ServerWriter< ::NavigationData>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamNavigationData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamNavigationData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamNavigationData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamNavigationData(::grpc::ServerContext* /*context*/, const ::StreamRequest* /*request*/, ::grpc::ServerWriter< ::NavigationData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamNavigationData(::grpc::ServerContext* context, ::StreamRequest* request, ::grpc::ServerAsyncWriter< ::NavigationData>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamNavigationData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamNavigationData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamNavigationData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::StreamRequest, ::NavigationData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::StreamRequest* request) { return this->StreamNavigationData(context, request); }));
    }
    ~WithCallbackMethod_StreamNavigationData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamNavigationData(::grpc::ServerContext* /*context*/, const ::StreamRequest* /*request*/, ::grpc::ServerWriter< ::NavigationData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::NavigationData>* StreamNavigationData(
      ::grpc::CallbackServerContext* /*context*/, const ::StreamRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamNavigationData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamNavigationData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamNavigationData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamNavigationData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamNavigationData(::grpc::ServerContext* /*context*/, const ::StreamRequest* /*request*/, ::grpc::ServerWriter< ::NavigationData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamNavigationData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamNavigationData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamNavigationData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamNavigationData(::grpc::ServerContext* /*context*/, const ::StreamRequest* /*request*/, ::grpc::ServerWriter< ::NavigationData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamNavigationData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamNavigationData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamNavigationData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamNavigationData(context, request); }));
    }
    ~WithRawCallbackMethod_StreamNavigationData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamNavigationData(::grpc::ServerContext* /*context*/, const ::StreamRequest* /*request*/, ::grpc::ServerWriter< ::NavigationData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamNavigationData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamNavigationData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamNavigationData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::StreamRequest, ::NavigationData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::StreamRequest, ::NavigationData>* streamer) {
                       return this->StreamedStreamNavigationData(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamNavigationData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamNavigationData(::grpc::ServerContext* /*context*/, const ::StreamRequest* /*request*/, ::grpc::ServerWriter< ::NavigationData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamNavigationData(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::StreamRequest,::NavigationData>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamNavigationData<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_StreamNavigationData<Service > StreamedService;
};


#endif  // GRPC_navigation_5fservice_2eproto__INCLUDED
