// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: navigation_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_navigation_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_navigation_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_navigation_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_navigation_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_navigation_5fservice_2eproto;
class DoubleField;
struct DoubleFieldDefaultTypeInternal;
extern DoubleFieldDefaultTypeInternal _DoubleField_default_instance_;
class NavigationData;
struct NavigationDataDefaultTypeInternal;
extern NavigationDataDefaultTypeInternal _NavigationData_default_instance_;
class StreamRequest;
struct StreamRequestDefaultTypeInternal;
extern StreamRequestDefaultTypeInternal _StreamRequest_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::DoubleField* Arena::CreateMaybeMessage<::DoubleField>(Arena*);
template<> ::NavigationData* Arena::CreateMaybeMessage<::NavigationData>(Arena*);
template<> ::StreamRequest* Arena::CreateMaybeMessage<::StreamRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class StreamRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:StreamRequest) */ {
 public:
  inline StreamRequest() : StreamRequest(nullptr) {}
  explicit PROTOBUF_CONSTEXPR StreamRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamRequest(const StreamRequest& from);
  StreamRequest(StreamRequest&& from) noexcept
    : StreamRequest() {
    *this = ::std::move(from);
  }

  inline StreamRequest& operator=(const StreamRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamRequest& operator=(StreamRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamRequest* internal_default_instance() {
    return reinterpret_cast<const StreamRequest*>(
               &_StreamRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StreamRequest& a, StreamRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const StreamRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const StreamRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "StreamRequest";
  }
  protected:
  explicit StreamRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:StreamRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_navigation_5fservice_2eproto;
};
// -------------------------------------------------------------------

class DoubleField final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DoubleField) */ {
 public:
  inline DoubleField() : DoubleField(nullptr) {}
  ~DoubleField() override;
  explicit PROTOBUF_CONSTEXPR DoubleField(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DoubleField(const DoubleField& from);
  DoubleField(DoubleField&& from) noexcept
    : DoubleField() {
    *this = ::std::move(from);
  }

  inline DoubleField& operator=(const DoubleField& from) {
    CopyFrom(from);
    return *this;
  }
  inline DoubleField& operator=(DoubleField&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DoubleField& default_instance() {
    return *internal_default_instance();
  }
  static inline const DoubleField* internal_default_instance() {
    return reinterpret_cast<const DoubleField*>(
               &_DoubleField_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DoubleField& a, DoubleField& b) {
    a.Swap(&b);
  }
  inline void Swap(DoubleField* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DoubleField* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DoubleField* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DoubleField>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DoubleField& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DoubleField& from) {
    DoubleField::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DoubleField* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DoubleField";
  }
  protected:
  explicit DoubleField(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
    kIsValidFieldNumber = 2,
  };
  // double value = 1;
  void clear_value();
  double value() const;
  void set_value(double value);
  private:
  double _internal_value() const;
  void _internal_set_value(double value);
  public:

  // bool is_valid = 2;
  void clear_is_valid();
  bool is_valid() const;
  void set_is_valid(bool value);
  private:
  bool _internal_is_valid() const;
  void _internal_set_is_valid(bool value);
  public:

  // @@protoc_insertion_point(class_scope:DoubleField)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double value_;
    bool is_valid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_navigation_5fservice_2eproto;
};
// -------------------------------------------------------------------

class NavigationData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NavigationData) */ {
 public:
  inline NavigationData() : NavigationData(nullptr) {}
  ~NavigationData() override;
  explicit PROTOBUF_CONSTEXPR NavigationData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NavigationData(const NavigationData& from);
  NavigationData(NavigationData&& from) noexcept
    : NavigationData() {
    *this = ::std::move(from);
  }

  inline NavigationData& operator=(const NavigationData& from) {
    CopyFrom(from);
    return *this;
  }
  inline NavigationData& operator=(NavigationData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NavigationData& default_instance() {
    return *internal_default_instance();
  }
  static inline const NavigationData* internal_default_instance() {
    return reinterpret_cast<const NavigationData*>(
               &_NavigationData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(NavigationData& a, NavigationData& b) {
    a.Swap(&b);
  }
  inline void Swap(NavigationData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NavigationData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NavigationData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NavigationData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NavigationData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NavigationData& from) {
    NavigationData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NavigationData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NavigationData";
  }
  protected:
  explicit NavigationData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLatitudeDdFieldNumber = 1,
    kLongitudeDdFieldNumber = 2,
    kHeadingRadFieldNumber = 3,
    kRelativeSpeedKnotsFieldNumber = 4,
    kRollRadFieldNumber = 5,
    kPitchRadFieldNumber = 6,
    kDriftSpeedMpsFieldNumber = 7,
    kDriftCourseMpsFieldNumber = 8,
  };
  // .DoubleField latitude_dd = 1;
  bool has_latitude_dd() const;
  private:
  bool _internal_has_latitude_dd() const;
  public:
  void clear_latitude_dd();
  const ::DoubleField& latitude_dd() const;
  PROTOBUF_NODISCARD ::DoubleField* release_latitude_dd();
  ::DoubleField* mutable_latitude_dd();
  void set_allocated_latitude_dd(::DoubleField* latitude_dd);
  private:
  const ::DoubleField& _internal_latitude_dd() const;
  ::DoubleField* _internal_mutable_latitude_dd();
  public:
  void unsafe_arena_set_allocated_latitude_dd(
      ::DoubleField* latitude_dd);
  ::DoubleField* unsafe_arena_release_latitude_dd();

  // .DoubleField longitude_dd = 2;
  bool has_longitude_dd() const;
  private:
  bool _internal_has_longitude_dd() const;
  public:
  void clear_longitude_dd();
  const ::DoubleField& longitude_dd() const;
  PROTOBUF_NODISCARD ::DoubleField* release_longitude_dd();
  ::DoubleField* mutable_longitude_dd();
  void set_allocated_longitude_dd(::DoubleField* longitude_dd);
  private:
  const ::DoubleField& _internal_longitude_dd() const;
  ::DoubleField* _internal_mutable_longitude_dd();
  public:
  void unsafe_arena_set_allocated_longitude_dd(
      ::DoubleField* longitude_dd);
  ::DoubleField* unsafe_arena_release_longitude_dd();

  // .DoubleField heading_rad = 3;
  bool has_heading_rad() const;
  private:
  bool _internal_has_heading_rad() const;
  public:
  void clear_heading_rad();
  const ::DoubleField& heading_rad() const;
  PROTOBUF_NODISCARD ::DoubleField* release_heading_rad();
  ::DoubleField* mutable_heading_rad();
  void set_allocated_heading_rad(::DoubleField* heading_rad);
  private:
  const ::DoubleField& _internal_heading_rad() const;
  ::DoubleField* _internal_mutable_heading_rad();
  public:
  void unsafe_arena_set_allocated_heading_rad(
      ::DoubleField* heading_rad);
  ::DoubleField* unsafe_arena_release_heading_rad();

  // .DoubleField relative_speed_knots = 4;
  bool has_relative_speed_knots() const;
  private:
  bool _internal_has_relative_speed_knots() const;
  public:
  void clear_relative_speed_knots();
  const ::DoubleField& relative_speed_knots() const;
  PROTOBUF_NODISCARD ::DoubleField* release_relative_speed_knots();
  ::DoubleField* mutable_relative_speed_knots();
  void set_allocated_relative_speed_knots(::DoubleField* relative_speed_knots);
  private:
  const ::DoubleField& _internal_relative_speed_knots() const;
  ::DoubleField* _internal_mutable_relative_speed_knots();
  public:
  void unsafe_arena_set_allocated_relative_speed_knots(
      ::DoubleField* relative_speed_knots);
  ::DoubleField* unsafe_arena_release_relative_speed_knots();

  // .DoubleField roll_rad = 5;
  bool has_roll_rad() const;
  private:
  bool _internal_has_roll_rad() const;
  public:
  void clear_roll_rad();
  const ::DoubleField& roll_rad() const;
  PROTOBUF_NODISCARD ::DoubleField* release_roll_rad();
  ::DoubleField* mutable_roll_rad();
  void set_allocated_roll_rad(::DoubleField* roll_rad);
  private:
  const ::DoubleField& _internal_roll_rad() const;
  ::DoubleField* _internal_mutable_roll_rad();
  public:
  void unsafe_arena_set_allocated_roll_rad(
      ::DoubleField* roll_rad);
  ::DoubleField* unsafe_arena_release_roll_rad();

  // .DoubleField pitch_rad = 6;
  bool has_pitch_rad() const;
  private:
  bool _internal_has_pitch_rad() const;
  public:
  void clear_pitch_rad();
  const ::DoubleField& pitch_rad() const;
  PROTOBUF_NODISCARD ::DoubleField* release_pitch_rad();
  ::DoubleField* mutable_pitch_rad();
  void set_allocated_pitch_rad(::DoubleField* pitch_rad);
  private:
  const ::DoubleField& _internal_pitch_rad() const;
  ::DoubleField* _internal_mutable_pitch_rad();
  public:
  void unsafe_arena_set_allocated_pitch_rad(
      ::DoubleField* pitch_rad);
  ::DoubleField* unsafe_arena_release_pitch_rad();

  // .DoubleField drift_speed_mps = 7;
  bool has_drift_speed_mps() const;
  private:
  bool _internal_has_drift_speed_mps() const;
  public:
  void clear_drift_speed_mps();
  const ::DoubleField& drift_speed_mps() const;
  PROTOBUF_NODISCARD ::DoubleField* release_drift_speed_mps();
  ::DoubleField* mutable_drift_speed_mps();
  void set_allocated_drift_speed_mps(::DoubleField* drift_speed_mps);
  private:
  const ::DoubleField& _internal_drift_speed_mps() const;
  ::DoubleField* _internal_mutable_drift_speed_mps();
  public:
  void unsafe_arena_set_allocated_drift_speed_mps(
      ::DoubleField* drift_speed_mps);
  ::DoubleField* unsafe_arena_release_drift_speed_mps();

  // .DoubleField drift_course_mps = 8;
  bool has_drift_course_mps() const;
  private:
  bool _internal_has_drift_course_mps() const;
  public:
  void clear_drift_course_mps();
  const ::DoubleField& drift_course_mps() const;
  PROTOBUF_NODISCARD ::DoubleField* release_drift_course_mps();
  ::DoubleField* mutable_drift_course_mps();
  void set_allocated_drift_course_mps(::DoubleField* drift_course_mps);
  private:
  const ::DoubleField& _internal_drift_course_mps() const;
  ::DoubleField* _internal_mutable_drift_course_mps();
  public:
  void unsafe_arena_set_allocated_drift_course_mps(
      ::DoubleField* drift_course_mps);
  ::DoubleField* unsafe_arena_release_drift_course_mps();

  // @@protoc_insertion_point(class_scope:NavigationData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::DoubleField* latitude_dd_;
    ::DoubleField* longitude_dd_;
    ::DoubleField* heading_rad_;
    ::DoubleField* relative_speed_knots_;
    ::DoubleField* roll_rad_;
    ::DoubleField* pitch_rad_;
    ::DoubleField* drift_speed_mps_;
    ::DoubleField* drift_course_mps_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_navigation_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StreamRequest

// -------------------------------------------------------------------

// DoubleField

// double value = 1;
inline void DoubleField::clear_value() {
  _impl_.value_ = 0;
}
inline double DoubleField::_internal_value() const {
  return _impl_.value_;
}
inline double DoubleField::value() const {
  // @@protoc_insertion_point(field_get:DoubleField.value)
  return _internal_value();
}
inline void DoubleField::_internal_set_value(double value) {
  
  _impl_.value_ = value;
}
inline void DoubleField::set_value(double value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:DoubleField.value)
}

// bool is_valid = 2;
inline void DoubleField::clear_is_valid() {
  _impl_.is_valid_ = false;
}
inline bool DoubleField::_internal_is_valid() const {
  return _impl_.is_valid_;
}
inline bool DoubleField::is_valid() const {
  // @@protoc_insertion_point(field_get:DoubleField.is_valid)
  return _internal_is_valid();
}
inline void DoubleField::_internal_set_is_valid(bool value) {
  
  _impl_.is_valid_ = value;
}
inline void DoubleField::set_is_valid(bool value) {
  _internal_set_is_valid(value);
  // @@protoc_insertion_point(field_set:DoubleField.is_valid)
}

// -------------------------------------------------------------------

// NavigationData

// .DoubleField latitude_dd = 1;
inline bool NavigationData::_internal_has_latitude_dd() const {
  return this != internal_default_instance() && _impl_.latitude_dd_ != nullptr;
}
inline bool NavigationData::has_latitude_dd() const {
  return _internal_has_latitude_dd();
}
inline void NavigationData::clear_latitude_dd() {
  if (GetArenaForAllocation() == nullptr && _impl_.latitude_dd_ != nullptr) {
    delete _impl_.latitude_dd_;
  }
  _impl_.latitude_dd_ = nullptr;
}
inline const ::DoubleField& NavigationData::_internal_latitude_dd() const {
  const ::DoubleField* p = _impl_.latitude_dd_;
  return p != nullptr ? *p : reinterpret_cast<const ::DoubleField&>(
      ::_DoubleField_default_instance_);
}
inline const ::DoubleField& NavigationData::latitude_dd() const {
  // @@protoc_insertion_point(field_get:NavigationData.latitude_dd)
  return _internal_latitude_dd();
}
inline void NavigationData::unsafe_arena_set_allocated_latitude_dd(
    ::DoubleField* latitude_dd) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.latitude_dd_);
  }
  _impl_.latitude_dd_ = latitude_dd;
  if (latitude_dd) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NavigationData.latitude_dd)
}
inline ::DoubleField* NavigationData::release_latitude_dd() {
  
  ::DoubleField* temp = _impl_.latitude_dd_;
  _impl_.latitude_dd_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::DoubleField* NavigationData::unsafe_arena_release_latitude_dd() {
  // @@protoc_insertion_point(field_release:NavigationData.latitude_dd)
  
  ::DoubleField* temp = _impl_.latitude_dd_;
  _impl_.latitude_dd_ = nullptr;
  return temp;
}
inline ::DoubleField* NavigationData::_internal_mutable_latitude_dd() {
  
  if (_impl_.latitude_dd_ == nullptr) {
    auto* p = CreateMaybeMessage<::DoubleField>(GetArenaForAllocation());
    _impl_.latitude_dd_ = p;
  }
  return _impl_.latitude_dd_;
}
inline ::DoubleField* NavigationData::mutable_latitude_dd() {
  ::DoubleField* _msg = _internal_mutable_latitude_dd();
  // @@protoc_insertion_point(field_mutable:NavigationData.latitude_dd)
  return _msg;
}
inline void NavigationData::set_allocated_latitude_dd(::DoubleField* latitude_dd) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.latitude_dd_;
  }
  if (latitude_dd) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(latitude_dd);
    if (message_arena != submessage_arena) {
      latitude_dd = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, latitude_dd, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.latitude_dd_ = latitude_dd;
  // @@protoc_insertion_point(field_set_allocated:NavigationData.latitude_dd)
}

// .DoubleField longitude_dd = 2;
inline bool NavigationData::_internal_has_longitude_dd() const {
  return this != internal_default_instance() && _impl_.longitude_dd_ != nullptr;
}
inline bool NavigationData::has_longitude_dd() const {
  return _internal_has_longitude_dd();
}
inline void NavigationData::clear_longitude_dd() {
  if (GetArenaForAllocation() == nullptr && _impl_.longitude_dd_ != nullptr) {
    delete _impl_.longitude_dd_;
  }
  _impl_.longitude_dd_ = nullptr;
}
inline const ::DoubleField& NavigationData::_internal_longitude_dd() const {
  const ::DoubleField* p = _impl_.longitude_dd_;
  return p != nullptr ? *p : reinterpret_cast<const ::DoubleField&>(
      ::_DoubleField_default_instance_);
}
inline const ::DoubleField& NavigationData::longitude_dd() const {
  // @@protoc_insertion_point(field_get:NavigationData.longitude_dd)
  return _internal_longitude_dd();
}
inline void NavigationData::unsafe_arena_set_allocated_longitude_dd(
    ::DoubleField* longitude_dd) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.longitude_dd_);
  }
  _impl_.longitude_dd_ = longitude_dd;
  if (longitude_dd) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NavigationData.longitude_dd)
}
inline ::DoubleField* NavigationData::release_longitude_dd() {
  
  ::DoubleField* temp = _impl_.longitude_dd_;
  _impl_.longitude_dd_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::DoubleField* NavigationData::unsafe_arena_release_longitude_dd() {
  // @@protoc_insertion_point(field_release:NavigationData.longitude_dd)
  
  ::DoubleField* temp = _impl_.longitude_dd_;
  _impl_.longitude_dd_ = nullptr;
  return temp;
}
inline ::DoubleField* NavigationData::_internal_mutable_longitude_dd() {
  
  if (_impl_.longitude_dd_ == nullptr) {
    auto* p = CreateMaybeMessage<::DoubleField>(GetArenaForAllocation());
    _impl_.longitude_dd_ = p;
  }
  return _impl_.longitude_dd_;
}
inline ::DoubleField* NavigationData::mutable_longitude_dd() {
  ::DoubleField* _msg = _internal_mutable_longitude_dd();
  // @@protoc_insertion_point(field_mutable:NavigationData.longitude_dd)
  return _msg;
}
inline void NavigationData::set_allocated_longitude_dd(::DoubleField* longitude_dd) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.longitude_dd_;
  }
  if (longitude_dd) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(longitude_dd);
    if (message_arena != submessage_arena) {
      longitude_dd = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, longitude_dd, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.longitude_dd_ = longitude_dd;
  // @@protoc_insertion_point(field_set_allocated:NavigationData.longitude_dd)
}

// .DoubleField heading_rad = 3;
inline bool NavigationData::_internal_has_heading_rad() const {
  return this != internal_default_instance() && _impl_.heading_rad_ != nullptr;
}
inline bool NavigationData::has_heading_rad() const {
  return _internal_has_heading_rad();
}
inline void NavigationData::clear_heading_rad() {
  if (GetArenaForAllocation() == nullptr && _impl_.heading_rad_ != nullptr) {
    delete _impl_.heading_rad_;
  }
  _impl_.heading_rad_ = nullptr;
}
inline const ::DoubleField& NavigationData::_internal_heading_rad() const {
  const ::DoubleField* p = _impl_.heading_rad_;
  return p != nullptr ? *p : reinterpret_cast<const ::DoubleField&>(
      ::_DoubleField_default_instance_);
}
inline const ::DoubleField& NavigationData::heading_rad() const {
  // @@protoc_insertion_point(field_get:NavigationData.heading_rad)
  return _internal_heading_rad();
}
inline void NavigationData::unsafe_arena_set_allocated_heading_rad(
    ::DoubleField* heading_rad) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.heading_rad_);
  }
  _impl_.heading_rad_ = heading_rad;
  if (heading_rad) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NavigationData.heading_rad)
}
inline ::DoubleField* NavigationData::release_heading_rad() {
  
  ::DoubleField* temp = _impl_.heading_rad_;
  _impl_.heading_rad_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::DoubleField* NavigationData::unsafe_arena_release_heading_rad() {
  // @@protoc_insertion_point(field_release:NavigationData.heading_rad)
  
  ::DoubleField* temp = _impl_.heading_rad_;
  _impl_.heading_rad_ = nullptr;
  return temp;
}
inline ::DoubleField* NavigationData::_internal_mutable_heading_rad() {
  
  if (_impl_.heading_rad_ == nullptr) {
    auto* p = CreateMaybeMessage<::DoubleField>(GetArenaForAllocation());
    _impl_.heading_rad_ = p;
  }
  return _impl_.heading_rad_;
}
inline ::DoubleField* NavigationData::mutable_heading_rad() {
  ::DoubleField* _msg = _internal_mutable_heading_rad();
  // @@protoc_insertion_point(field_mutable:NavigationData.heading_rad)
  return _msg;
}
inline void NavigationData::set_allocated_heading_rad(::DoubleField* heading_rad) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.heading_rad_;
  }
  if (heading_rad) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(heading_rad);
    if (message_arena != submessage_arena) {
      heading_rad = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, heading_rad, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.heading_rad_ = heading_rad;
  // @@protoc_insertion_point(field_set_allocated:NavigationData.heading_rad)
}

// .DoubleField relative_speed_knots = 4;
inline bool NavigationData::_internal_has_relative_speed_knots() const {
  return this != internal_default_instance() && _impl_.relative_speed_knots_ != nullptr;
}
inline bool NavigationData::has_relative_speed_knots() const {
  return _internal_has_relative_speed_knots();
}
inline void NavigationData::clear_relative_speed_knots() {
  if (GetArenaForAllocation() == nullptr && _impl_.relative_speed_knots_ != nullptr) {
    delete _impl_.relative_speed_knots_;
  }
  _impl_.relative_speed_knots_ = nullptr;
}
inline const ::DoubleField& NavigationData::_internal_relative_speed_knots() const {
  const ::DoubleField* p = _impl_.relative_speed_knots_;
  return p != nullptr ? *p : reinterpret_cast<const ::DoubleField&>(
      ::_DoubleField_default_instance_);
}
inline const ::DoubleField& NavigationData::relative_speed_knots() const {
  // @@protoc_insertion_point(field_get:NavigationData.relative_speed_knots)
  return _internal_relative_speed_knots();
}
inline void NavigationData::unsafe_arena_set_allocated_relative_speed_knots(
    ::DoubleField* relative_speed_knots) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.relative_speed_knots_);
  }
  _impl_.relative_speed_knots_ = relative_speed_knots;
  if (relative_speed_knots) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NavigationData.relative_speed_knots)
}
inline ::DoubleField* NavigationData::release_relative_speed_knots() {
  
  ::DoubleField* temp = _impl_.relative_speed_knots_;
  _impl_.relative_speed_knots_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::DoubleField* NavigationData::unsafe_arena_release_relative_speed_knots() {
  // @@protoc_insertion_point(field_release:NavigationData.relative_speed_knots)
  
  ::DoubleField* temp = _impl_.relative_speed_knots_;
  _impl_.relative_speed_knots_ = nullptr;
  return temp;
}
inline ::DoubleField* NavigationData::_internal_mutable_relative_speed_knots() {
  
  if (_impl_.relative_speed_knots_ == nullptr) {
    auto* p = CreateMaybeMessage<::DoubleField>(GetArenaForAllocation());
    _impl_.relative_speed_knots_ = p;
  }
  return _impl_.relative_speed_knots_;
}
inline ::DoubleField* NavigationData::mutable_relative_speed_knots() {
  ::DoubleField* _msg = _internal_mutable_relative_speed_knots();
  // @@protoc_insertion_point(field_mutable:NavigationData.relative_speed_knots)
  return _msg;
}
inline void NavigationData::set_allocated_relative_speed_knots(::DoubleField* relative_speed_knots) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.relative_speed_knots_;
  }
  if (relative_speed_knots) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(relative_speed_knots);
    if (message_arena != submessage_arena) {
      relative_speed_knots = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, relative_speed_knots, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.relative_speed_knots_ = relative_speed_knots;
  // @@protoc_insertion_point(field_set_allocated:NavigationData.relative_speed_knots)
}

// .DoubleField roll_rad = 5;
inline bool NavigationData::_internal_has_roll_rad() const {
  return this != internal_default_instance() && _impl_.roll_rad_ != nullptr;
}
inline bool NavigationData::has_roll_rad() const {
  return _internal_has_roll_rad();
}
inline void NavigationData::clear_roll_rad() {
  if (GetArenaForAllocation() == nullptr && _impl_.roll_rad_ != nullptr) {
    delete _impl_.roll_rad_;
  }
  _impl_.roll_rad_ = nullptr;
}
inline const ::DoubleField& NavigationData::_internal_roll_rad() const {
  const ::DoubleField* p = _impl_.roll_rad_;
  return p != nullptr ? *p : reinterpret_cast<const ::DoubleField&>(
      ::_DoubleField_default_instance_);
}
inline const ::DoubleField& NavigationData::roll_rad() const {
  // @@protoc_insertion_point(field_get:NavigationData.roll_rad)
  return _internal_roll_rad();
}
inline void NavigationData::unsafe_arena_set_allocated_roll_rad(
    ::DoubleField* roll_rad) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.roll_rad_);
  }
  _impl_.roll_rad_ = roll_rad;
  if (roll_rad) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NavigationData.roll_rad)
}
inline ::DoubleField* NavigationData::release_roll_rad() {
  
  ::DoubleField* temp = _impl_.roll_rad_;
  _impl_.roll_rad_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::DoubleField* NavigationData::unsafe_arena_release_roll_rad() {
  // @@protoc_insertion_point(field_release:NavigationData.roll_rad)
  
  ::DoubleField* temp = _impl_.roll_rad_;
  _impl_.roll_rad_ = nullptr;
  return temp;
}
inline ::DoubleField* NavigationData::_internal_mutable_roll_rad() {
  
  if (_impl_.roll_rad_ == nullptr) {
    auto* p = CreateMaybeMessage<::DoubleField>(GetArenaForAllocation());
    _impl_.roll_rad_ = p;
  }
  return _impl_.roll_rad_;
}
inline ::DoubleField* NavigationData::mutable_roll_rad() {
  ::DoubleField* _msg = _internal_mutable_roll_rad();
  // @@protoc_insertion_point(field_mutable:NavigationData.roll_rad)
  return _msg;
}
inline void NavigationData::set_allocated_roll_rad(::DoubleField* roll_rad) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.roll_rad_;
  }
  if (roll_rad) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(roll_rad);
    if (message_arena != submessage_arena) {
      roll_rad = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, roll_rad, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.roll_rad_ = roll_rad;
  // @@protoc_insertion_point(field_set_allocated:NavigationData.roll_rad)
}

// .DoubleField pitch_rad = 6;
inline bool NavigationData::_internal_has_pitch_rad() const {
  return this != internal_default_instance() && _impl_.pitch_rad_ != nullptr;
}
inline bool NavigationData::has_pitch_rad() const {
  return _internal_has_pitch_rad();
}
inline void NavigationData::clear_pitch_rad() {
  if (GetArenaForAllocation() == nullptr && _impl_.pitch_rad_ != nullptr) {
    delete _impl_.pitch_rad_;
  }
  _impl_.pitch_rad_ = nullptr;
}
inline const ::DoubleField& NavigationData::_internal_pitch_rad() const {
  const ::DoubleField* p = _impl_.pitch_rad_;
  return p != nullptr ? *p : reinterpret_cast<const ::DoubleField&>(
      ::_DoubleField_default_instance_);
}
inline const ::DoubleField& NavigationData::pitch_rad() const {
  // @@protoc_insertion_point(field_get:NavigationData.pitch_rad)
  return _internal_pitch_rad();
}
inline void NavigationData::unsafe_arena_set_allocated_pitch_rad(
    ::DoubleField* pitch_rad) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pitch_rad_);
  }
  _impl_.pitch_rad_ = pitch_rad;
  if (pitch_rad) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NavigationData.pitch_rad)
}
inline ::DoubleField* NavigationData::release_pitch_rad() {
  
  ::DoubleField* temp = _impl_.pitch_rad_;
  _impl_.pitch_rad_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::DoubleField* NavigationData::unsafe_arena_release_pitch_rad() {
  // @@protoc_insertion_point(field_release:NavigationData.pitch_rad)
  
  ::DoubleField* temp = _impl_.pitch_rad_;
  _impl_.pitch_rad_ = nullptr;
  return temp;
}
inline ::DoubleField* NavigationData::_internal_mutable_pitch_rad() {
  
  if (_impl_.pitch_rad_ == nullptr) {
    auto* p = CreateMaybeMessage<::DoubleField>(GetArenaForAllocation());
    _impl_.pitch_rad_ = p;
  }
  return _impl_.pitch_rad_;
}
inline ::DoubleField* NavigationData::mutable_pitch_rad() {
  ::DoubleField* _msg = _internal_mutable_pitch_rad();
  // @@protoc_insertion_point(field_mutable:NavigationData.pitch_rad)
  return _msg;
}
inline void NavigationData::set_allocated_pitch_rad(::DoubleField* pitch_rad) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.pitch_rad_;
  }
  if (pitch_rad) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pitch_rad);
    if (message_arena != submessage_arena) {
      pitch_rad = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pitch_rad, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pitch_rad_ = pitch_rad;
  // @@protoc_insertion_point(field_set_allocated:NavigationData.pitch_rad)
}

// .DoubleField drift_speed_mps = 7;
inline bool NavigationData::_internal_has_drift_speed_mps() const {
  return this != internal_default_instance() && _impl_.drift_speed_mps_ != nullptr;
}
inline bool NavigationData::has_drift_speed_mps() const {
  return _internal_has_drift_speed_mps();
}
inline void NavigationData::clear_drift_speed_mps() {
  if (GetArenaForAllocation() == nullptr && _impl_.drift_speed_mps_ != nullptr) {
    delete _impl_.drift_speed_mps_;
  }
  _impl_.drift_speed_mps_ = nullptr;
}
inline const ::DoubleField& NavigationData::_internal_drift_speed_mps() const {
  const ::DoubleField* p = _impl_.drift_speed_mps_;
  return p != nullptr ? *p : reinterpret_cast<const ::DoubleField&>(
      ::_DoubleField_default_instance_);
}
inline const ::DoubleField& NavigationData::drift_speed_mps() const {
  // @@protoc_insertion_point(field_get:NavigationData.drift_speed_mps)
  return _internal_drift_speed_mps();
}
inline void NavigationData::unsafe_arena_set_allocated_drift_speed_mps(
    ::DoubleField* drift_speed_mps) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.drift_speed_mps_);
  }
  _impl_.drift_speed_mps_ = drift_speed_mps;
  if (drift_speed_mps) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NavigationData.drift_speed_mps)
}
inline ::DoubleField* NavigationData::release_drift_speed_mps() {
  
  ::DoubleField* temp = _impl_.drift_speed_mps_;
  _impl_.drift_speed_mps_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::DoubleField* NavigationData::unsafe_arena_release_drift_speed_mps() {
  // @@protoc_insertion_point(field_release:NavigationData.drift_speed_mps)
  
  ::DoubleField* temp = _impl_.drift_speed_mps_;
  _impl_.drift_speed_mps_ = nullptr;
  return temp;
}
inline ::DoubleField* NavigationData::_internal_mutable_drift_speed_mps() {
  
  if (_impl_.drift_speed_mps_ == nullptr) {
    auto* p = CreateMaybeMessage<::DoubleField>(GetArenaForAllocation());
    _impl_.drift_speed_mps_ = p;
  }
  return _impl_.drift_speed_mps_;
}
inline ::DoubleField* NavigationData::mutable_drift_speed_mps() {
  ::DoubleField* _msg = _internal_mutable_drift_speed_mps();
  // @@protoc_insertion_point(field_mutable:NavigationData.drift_speed_mps)
  return _msg;
}
inline void NavigationData::set_allocated_drift_speed_mps(::DoubleField* drift_speed_mps) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.drift_speed_mps_;
  }
  if (drift_speed_mps) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(drift_speed_mps);
    if (message_arena != submessage_arena) {
      drift_speed_mps = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, drift_speed_mps, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.drift_speed_mps_ = drift_speed_mps;
  // @@protoc_insertion_point(field_set_allocated:NavigationData.drift_speed_mps)
}

// .DoubleField drift_course_mps = 8;
inline bool NavigationData::_internal_has_drift_course_mps() const {
  return this != internal_default_instance() && _impl_.drift_course_mps_ != nullptr;
}
inline bool NavigationData::has_drift_course_mps() const {
  return _internal_has_drift_course_mps();
}
inline void NavigationData::clear_drift_course_mps() {
  if (GetArenaForAllocation() == nullptr && _impl_.drift_course_mps_ != nullptr) {
    delete _impl_.drift_course_mps_;
  }
  _impl_.drift_course_mps_ = nullptr;
}
inline const ::DoubleField& NavigationData::_internal_drift_course_mps() const {
  const ::DoubleField* p = _impl_.drift_course_mps_;
  return p != nullptr ? *p : reinterpret_cast<const ::DoubleField&>(
      ::_DoubleField_default_instance_);
}
inline const ::DoubleField& NavigationData::drift_course_mps() const {
  // @@protoc_insertion_point(field_get:NavigationData.drift_course_mps)
  return _internal_drift_course_mps();
}
inline void NavigationData::unsafe_arena_set_allocated_drift_course_mps(
    ::DoubleField* drift_course_mps) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.drift_course_mps_);
  }
  _impl_.drift_course_mps_ = drift_course_mps;
  if (drift_course_mps) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NavigationData.drift_course_mps)
}
inline ::DoubleField* NavigationData::release_drift_course_mps() {
  
  ::DoubleField* temp = _impl_.drift_course_mps_;
  _impl_.drift_course_mps_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::DoubleField* NavigationData::unsafe_arena_release_drift_course_mps() {
  // @@protoc_insertion_point(field_release:NavigationData.drift_course_mps)
  
  ::DoubleField* temp = _impl_.drift_course_mps_;
  _impl_.drift_course_mps_ = nullptr;
  return temp;
}
inline ::DoubleField* NavigationData::_internal_mutable_drift_course_mps() {
  
  if (_impl_.drift_course_mps_ == nullptr) {
    auto* p = CreateMaybeMessage<::DoubleField>(GetArenaForAllocation());
    _impl_.drift_course_mps_ = p;
  }
  return _impl_.drift_course_mps_;
}
inline ::DoubleField* NavigationData::mutable_drift_course_mps() {
  ::DoubleField* _msg = _internal_mutable_drift_course_mps();
  // @@protoc_insertion_point(field_mutable:NavigationData.drift_course_mps)
  return _msg;
}
inline void NavigationData::set_allocated_drift_course_mps(::DoubleField* drift_course_mps) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.drift_course_mps_;
  }
  if (drift_course_mps) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(drift_course_mps);
    if (message_arena != submessage_arena) {
      drift_course_mps = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, drift_course_mps, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.drift_course_mps_ = drift_course_mps;
  // @@protoc_insertion_point(field_set_allocated:NavigationData.drift_course_mps)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_navigation_5fservice_2eproto
